version: '3.9'

services:
  tasksmanagement:
    build: ./backend
    ports:
      -5000:5000
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=tasksmanagement
      - DB_HOST=db
      - JWT_SECRET=a09sd8as098f09sd8fa0sd9f8
    volumes:
      - ./backend:/task-management-wra
    container_name: tasksmanagement-api
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      -8080:8080
